# This is an example .goreleaser.yaml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    mod_timestamp: '{{ .CommitTimestamp }}'
  - id: darwin-arm64
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    mod_timestamp: '{{ .CommitTimestamp }}'

universal_binaries:
  - ids:
      - darwin-amd64
      - darwin-arm64
    replace: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "all" }}all{{ else }}{{ .Arch }}{{ end }}
    builds_info:
      group: root
      owner: root

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
