# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - run: go generate ./...
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Build with devmode
        run: |
          go build -v -tags devmode -o grew .
          ./grew --version


