# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
      - run: go build
      - run: mkdir -p coverageFiles coverageRaw
      - name: Run unit tests with coverage
        run: |
          go list ./... | grep -v /tests > unit_pkgs.txt
          go test -tags devmode -race -coverprofile=./coverageFiles/coverage_unit.txt -covermode=atomic $(cat unit_pkgs.txt)

#      - uses: codecov/codecov-action@v6
#        with:
#          fail_ci_if_error: 'false'
#          handle_no_reports_found: 'true'
#          skip_validation: 'true'
#          directory: ./coverageFiles
#          token: ${{ secrets.CODECOV_TOKEN }}
