name: Live E2E Tests
on:
  schedule:
    - cron: '0 0 * * *' # Run daily
  workflow_dispatch:      # Allow manual triggers
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  smoke:
    strategy:
      matrix:
        os: [macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true

      - run: mkdir -p coverageFiles coverageRaw
      - name: Run smoke tests with coverage
        run: |
          GOCOVERDIR=$GITHUB_WORKSPACE/coverageRaw go test -v -timeout 15m -tags "devmode" -cover -coverpkg=./... ./tests/smoke

  e2e:
    strategy:
      matrix:
        os: [macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
      
      - run: mkdir -p coverageFiles coverageRaw
      - name: Run TestLiveEndToEnd
        run: |
          GOCOVERDIR=$GITHUB_WORKSPACE/coverageRaw go test -v -timeout 15m -tags "devmode" -cover -coverpkg=./... ./tests/e2e -run TestLiveEndToEnd

  integration:
    strategy:
      matrix:
        os: [macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true

      - run: mkdir -p coverageFiles coverageRaw
      - name: Run integration tests with coverage
        run: |
          GOCOVERDIR=$GITHUB_WORKSPACE/coverageRaw go test -v -timeout 15m -tags "devmode" -cover -coverpkg=./... ./tests/integration

#          go tool covdata textfmt -i=$GITHUB_WORKSPACE/coverageRaw -o ./coverageFiles/coverage_integration.txt
#      - uses: codecov/codecov-action@v6
#        with:
#          fail_ci_if_error: false
#          directory: ./coverageFiles
#          token: ${{ secrets.CODECOV_TOKEN }}

