name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
      - name: Install mkdmg
        run: go install al.essio.dev/cmd/mkdmg@latest
      - uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate DMG
        id: dmg
        run: |
          which hdiutil
          mkdir -p dist-dmg
          for arch in arm64 x86_64; do
            mkdir "dist_$(arch)"
            tar xvf dist/grew_Darwin_$(arch).tar.gz
            $(go env GOPATH)/bin/mkdmg -v "Homegrew_$(arch).dmg" "grew_Darwin_$(arch)"/
          done
          echo "images_generated=true" >> $GITHUB_OUTPUT

      - name: Upload DMGs to Release
        if: steps.dmg.outputs.images_generated == 'true'
        uses: softprops/action-gh-release@v3
        with:
          files: dist-dmg/*

#      - name: Install bsdiff
#        run: brew install bsdiff


#      - name: Generate Binary Patches
#        id: patcher
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          # Find the previous semantic version tag
#          PREV_TAG=$(git tag --sort=-v:refname | grep -v "^${{ github.ref_name }}$" | head -n 1)
#
#          if [ -z "$PREV_TAG" ]; then
#            echo "No previous tag found. Skipping patch generation."
#            exit 0
#          fi
#
#          echo "Generating patches from $PREV_TAG to ${{ github.ref_name }}"
#          mkdir -p dist-patches
#
#          # Allow some time for GoReleaser assets to be fully available via the API
#          sleep 10
#
#          go run tools/patcher/main.go -v -D dist-patches/ "$PREV_TAG" "${{ github.ref_name }}"
#          echo "patches_generated=true" >> $GITHUB_OUTPUT
#
#      - name: Upload Patches to Release
#        if: steps.patcher.outputs.patches_generated == 'true'
#        uses: softprops/action-gh-release@v3
#        with:
#          files: dist-patches/*
